using System;
using System.Threading;
using System.Threading.Tasks;
using Discord;
using Discord.WebSocket;

namespace BasicBot
{
 
    class Program
    {
        static string logdirectory = Environment.CurrentDirectory + @"\logs\";
        static string[] blacklistedstuff = { "discrodsteam.ru", "discordapp.click", "steamnitro.com", "gave-nitro.com", "stleam-hype.ru", "dlscord-app.com", "discord-nltro.com", "discodnitro.info", "dlscord.click", "discordnitro.click", "discrod-glfts.com", "steamnltro.com", "nitro-drop.com", "discord-app.ru", "discord-airdrop.com", "dlscordgift.com", "dlscord-nitro.info", "discordsgift.info", "dlscord-nitro.link", "discord-give.ru", "dlscord-claim.com", "steam-nltro.ru", "steamnitros.ru", "steamnltros.ru", "steamdiscord.com", "dlscord-nitro.click", "dlscord-nltro.com", "discord-claim.com", "discord-gifts.shop", "discords-nitro.xyz", "discord-drop.xyz", "discorclapp.fun", "discord-app.live", "discord-game.ru", "discord-free-nitro.ru", "steamcomunity-nitro-free.ru", "discordapp.biz", "dlscordapp.info", "discord-click.shop", "discond-nitro.ru", "discrodapp.site", "discord-give.com", "steamdlscord.com", "discord-app.net", "discorcl.life", "discocrdapp.com", "discrodapp.ru", "gift-discord.shop", "discoapps.live", "dlscrodapp.ru", "discorcd.gift", "discorcl-app.fun", "discorcd.gifts", "dlscordgived.xyz", "dlscordsglfts.xyz", "dicsordgift.com", "axieroll.com", "steam-dlscord.com", "discord-up.ru", "discocrd-nitro.com", "discorcdapp.com", "steam-discords.com", "discords-app.com", "boost-discord.com", "discord-halloween.com", "dropskeys.com", "discordsteam.com", "discrod-up.ru", "discord-app.me", "telegra.ph", "apps-nitro.com", "discorclapp.com", "dlscordsteam.com", "nitro-up.com", "discord-apps.info", "discrodup.ru", "dlscord-app.info", "discord-give.org", "dlscord.org", "discocrd.gift", "discordcommunlty.com", "nitro", "Nitro" };
        private readonly DiscordSocketClient _client;

        
        static void Main(string[] args)
            => new Program()
                .MainAsync()
                .GetAwaiter()
                .GetResult();

        public Program()
        {
         
            _client = new DiscordSocketClient();

            
            _client.Log += LogAsync;
            _client.Ready += ReadyAsync;
            _client.MessageReceived += MessageReceivedAsync;
           
        }

        public async Task MainAsync()
        {
            Console.Write("Token: ");
            // Tokens should be considered secret data, and never hard-coded.
            await _client.LoginAsync(TokenType.User, Console.ReadLine());
            

            await _client.StartAsync();

            // Block the program until it is closed.
            await Task.Delay(Timeout.Infinite);
        }

        private Task LogAsync(LogMessage log)
        {
            Console.WriteLine(log.ToString());
            return Task.CompletedTask;
        }

        // The Ready event indicates that the client has opened a
        // connection and it is now safe to access the cache.
        private Task ReadyAsync()
        {
            Console.WriteLine($"{_client.CurrentUser} is connected!");

            return Task.CompletedTask;
        }

        // This is not the recommended way to write a bot - consider
        // reading over the Commands Framework sample.
        private async Task MessageReceivedAsync(SocketMessage Message)
        {

            if (Message.Channel is IDMChannel dm)
            {
                for (int i = 0; i < blacklistedstuff.Length; i++)
                {

                    if (Message.Content.Contains(blacklistedstuff[i]) )
                    {
                        DateTime localDate = DateTime.Now;

                        Message.Channel.SendMessageAsync("Your message contains a phrase that may mean its a scam. The message you sent has been loged as well as your id. This Message Was Generated By Andrew Cavallo's Discord Scam Protector. For more information, go to https://github.com/Awire9966/DiscordScamProtector.");
                        File.WriteAllText(logdirectory + localDate.Month + "." + localDate.Day + "." + localDate.Year + " at " + localDate.Hour + "." + localDate.Minute + ".log", Message.Content + "\n User id:" + Message.Author.Id);
                    }

                }
            }
        }

       
        
    }
}